### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [butterflyfree/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

```
     - [ ] Your name
     - [ ] Where you are from
     - [ ] A favorite food
     - [ ] A hobby
```

**Comment by butterflyfree** [comment]
# Amethyst Ribble

## I am from God and made according to plan.

## My favorite food is Italian.

## I enjoy coding and website design. As well as learning new technology info.
